site_name: Enterprise Azure ML DevOps Playbook
nav:
  - Home: docs/index.md
  - Executive Overview: docs/01-executive-overview.md
  - Azure DevOps Foundations: docs/02-azure-devops-foundations.md
  - Repository Strategy: docs/03-repository.md
  - Connection: docs/04.md
  - Self Hosted Agents: docs/05-self-hosted-agents.md
  - Private Networking: docs/06-private-networking.md
  - Azure ML Workspace: docs/07-azure-ml-workspace.md
  - CI Pipeline: docs/08-ci-pipeline.md
  - Delivery Pipeline: docs/09-delivery-pipeline.md
  - MLOps Lifecycle: docs/10-mlops-lifecycle.md
  - Infrastructure as Code: docs/11-infrastructure-as-code.md
  - Security and Governance: docs/12-security-governance.md
  - Operations: docs/13-operations.md
  - Troubleshooting: docs/14-troubleshooting.md
  - Labs: docs/15-labs.md
  - Architecture Checklist: docs/16-architecture-checklist.md
  - Self Hosted Agent Build Guide: docs/17-self-hosted-agent-build-guide.md
  - Private Endpoint DNS Guide: docs/18-private-endpoint-dns-guide.md
