const solutionBlueprints={
 'secure-workbench':{solution:'Deploy a minimal secure Azure ML workbench: workspace, storage, Key Vault, ACR, Application Insights, Log Analytics, compute instance, CPU cluster, GPU cluster, model registry, and one test managed online endpoint. Use Azure/mlops-v2 as the enterprise scaffold and simplify it to one Dev/Test environment.',components:['Azure ML workspace','Storage datastore','Key Vault','ACR','App Insights','Log Analytics','Compute instance','CPU and GPU clusters','Managed online endpoint'],steps:['Create resource group and core services','Attach workspace dependencies','Deploy compute and autoscale clusters','Run sample experiment and register model','Deploy one endpoint and capture evidence'],source:'Azure MLOps v2 solution accelerator',url:'https://github.com/Azure/mlops-v2'},
 'landing-zone':{solution:'Create a workload-spoke package that fits the customer landing zone: resource group layout, approved naming, tags, diagnostics, policy checks, budget alert, and deployment parameters. Do not deploy a new landing zone.',components:['Workload subscription','Resource groups','Azure Policy','Tags','Diagnostic settings','Budget alert','Private DNS links'],steps:['Confirm landing-zone guardrails','Prepare environment parameters','Deploy workload resources','Validate policy and diagnostics','Document exceptions'],source:'Azure MLOps v2 documentation',url:'https://github.com/Azure/mlops-v2/tree/main/documentation'},
 'private-network':{solution:'Use customer-managed private networking for Azure ML and dependencies: private endpoint for workspace, Storage, Key Vault, and ACR, private DNS zone links, and self-hosted DevOps agent if required.',components:['Workspace private endpoint','Storage private endpoint','Key Vault private endpoint','ACR private endpoint','Private DNS zones','VNet links','Firewall validation'],steps:['Confirm subnet and DNS ownership','Create private endpoints','Link private DNS zones','Validate user and agent connectivity','Disable public access after private path is proven'],source:'Secure Azure ML workspace with VNet',url:'https://learn.microsoft.com/en-us/azure/machine-learning/how-to-secure-workspace-vnet'},
 'identity-rbac':{solution:'Use Entra groups and workload identities. Define groups for Data Scientists, ML Engineers, Platform Operators, Security Reviewers, and Approvers. Prefer managed identity or workload identity federation for pipelines.',components:['Entra groups','Azure RBAC','Workspace roles','Managed identity','Key Vault access','Azure DevOps service connection'],steps:['Map personas to groups','Assign least privilege roles','Configure pipeline identity','Validate Key Vault and datastore access','Document approval ownership'],source:'Azure DevOps MLOps authentication guidance',url:'https://learn.microsoft.com/en-us/azure/machine-learning/how-to-setup-mlops-azureml'},
 'dev-env':{solution:'Create one compute instance per approved data scientist with auto-shutdown, approved environments, datastore access, and sample notebooks. Keep notebooks for exploration and move repeatable work into jobs.',components:['Compute instance','Curated environment','Notebook samples','Datastore','MLflow tracking','Auto-shutdown'],steps:['Create compute instances','Attach datastore','Run sample notebook','Log metrics with MLflow','Convert repeatable steps into jobs'],source:'Azure ML examples',url:'https://github.com/Azure/azureml-examples'},
 'feature-batch':{solution:'Implement a reusable Azure ML pipeline component for feature preparation on CPU compute. Read from approved datastore, write prepared features/artifacts back to Storage, and version YAML in repo.',components:['CPU cluster','Data asset','Pipeline component','Command job YAML','Feature output','Artifact storage'],steps:['Create CPU cluster min nodes zero','Register data asset','Create feature component','Run pipeline job','Persist output and lineage'],source:'Azure ML pipeline component examples',url:'https://github.com/Azure/azureml-examples/tree/main/cli/jobs/pipelines-with-components'},
 'gpu-training':{solution:'Create an on-demand GPU cluster with min nodes zero and quota validated. Run one training job that logs parameters, metrics, artifacts, and model output to MLflow. Restrict GPU to approved jobs.',components:['GPU cluster','Training script','Environment YAML','MLflow logging','Run artifacts','Model candidate'],steps:['Confirm GPU quota','Create GPU cluster','Submit training job','Track metrics and artifacts','Promote candidate only after threshold'],source:'Azure ML job examples',url:'https://github.com/Azure/azureml-examples/tree/main/cli/jobs'},
 'registry-promotion':{solution:'Use Azure ML model registry for versioned lifecycle. Add an evaluation job and manual Azure DevOps approval gate before endpoint deployment. Tag models as candidate, approved, deployed, rejected, and rollback.',components:['Evaluation job','Model registry','Model tags','Azure DevOps approval','Release notes','Rollback version'],steps:['Evaluate model metrics','Register versioned model','Apply approval gate','Deploy approved model','Record rollback version'],source:'Azure DevOps MLOps with Azure ML',url:'https://learn.microsoft.com/en-us/azure/machine-learning/how-to-setup-mlops-azureml'},
 'online-serving':{solution:'Deploy the approved model to an Azure ML managed online endpoint using CLI v2 YAML. Use blue/green deployment names, smoke test the endpoint, and shift traffic only after validation.',components:['Endpoint YAML','Deployment YAML','Scoring script','Environment','Traffic routing','Smoke test','Telemetry'],steps:['Create endpoint','Create blue deployment','Run smoke test','Shift traffic','Keep previous deployment for rollback'],source:'Azure ML managed online endpoint examples',url:'https://github.com/Azure/azureml-examples/tree/main/cli/endpoints/online'},
 'web-observability':{solution:'Use Azure Container Apps for a lightweight internal web UI that calls the online endpoint. Add a batch endpoint pattern for offline scoring and send telemetry to Application Insights and Log Analytics.',components:['Azure Container Apps','Online endpoint client','Batch endpoint','Application Insights','Log Analytics','KQL queries','Runbook'],steps:['Deploy internal web UI','Configure endpoint auth and network path','Create batch endpoint example','Validate telemetry','Document KQL and ownership'],source:'Azure ML endpoint examples',url:'https://github.com/Azure/azureml-examples/tree/main/cli/endpoints'}
};
function enhanceSolutionDetail(id){const item=solutionBlueprints[id];const detail=document.getElementById('architecture-detail');if(!item||!detail)return;const card=document.querySelector(`.diagram-card[data-id="${id}"]`);const title=card?.querySelector('h3')?.textContent||'Architecture view';const summary=card?.querySelector('p')?.textContent||'';detail.innerHTML=`<span class="badge">Actual solution</span><h3>${title}</h3><p>${summary}</p><h4>Solution blueprint</h4><p>${item.solution}</p><h4>Deployable components</h4><ul class="detail-list">${item.components.map(x=>`<li>${x}</li>`).join('')}</ul><h4>Implementation steps</h4><ul class="detail-list">${item.steps.map(x=>`<li>${x}</li>`).join('')}</ul><a class="button secondary" href="${item.url}" target="_blank" rel="noreferrer">Open reference: ${item.source}</a>`;}
function enhanceActiveSolution(){const active=document.querySelector('.diagram-card.active')||document.querySelector('.diagram-card');if(active)enhanceSolutionDetail(active.dataset.id)}
document.addEventListener('click',e=>{const card=e.target.closest('.diagram-card');if(card)setTimeout(()=>enhanceSolutionDetail(card.dataset.id),0);if(e.target.closest('#arch-filters .filter'))setTimeout(enhanceActiveSolution,0);});
setTimeout(enhanceActiveSolution,200);
